package pl.klimas7.ekwreader;

public enum Court {
    WL1A("Aleksandrów Kujawski"),
    SU1A("Augustów"),
    OL1Y("Bartoszyce"),
    PT1B("Bełchatów"),
    KA1B("Będzin"),
    LU1B("Biała podlaska"),
    RA2G("Białobrzegi"),
    KO1B("Białogard"),
    BI1B("Białystok"),
    BB1B("Bielsko-Biała"),
    BI1P("Bielsk Podlaski"),
    ZA1B("Biłgoraj"),
    OL1B("Biskupiec"),
    TR1O("BochniaR1O"),
    JG1B("Bolesławiec"),
    EL1B("Braniewo"),
    TO1B("Brodnica"),
    OP1B("Brzeg"),
    TR1B("Brzesko"),
    LD1B("Brzeziny"),
    KS1B("Brzozów"),
    KI1B("Busko Zdrój"),
    BY1B("Bydgoszcz"),
    KA1Y("Bytom"),
    SL1B("Bytów"),
    LU1C("Chełm"),
    TO1C("Chełmno"),
    PO1H("Chodzież"),
    SL1C("Chojnice"),
    KA1C("Chorzów"),
    SZ1C("Choszczno"),
    KR1C("Chrzanów"),
    PL1C("Ciechanów"),
    BB1C("Cieszyn"),
    PO2T("Czarnków"),
    KR1K("Czernichów"),
    CZ1C("Częstochowa"),
    SL1Z("Człuchów"),
    KA1D("Dąbrowa Górnicza"),
    TR1D("Dąbrowa Tarnowska"),
    RZ1D("Dębica"),
    KR2Y("Dobczyce"),
    KO1D("Drawsko Pomorskie"),
    EL1D("Działdowo"),
    SW1D("Dzierżoniów"),
    EL1E("Elbląg"),
    OL1E("Ełk"),
    SI1G("Garwolin"),
    GD1G("Gdańsk"),
    GD1Y("Gdynia"),
    OL1G("Giżycko"),
    GL1G("Gliwice"),
    LE1G("Głogów"),
    OP1G("Głubczyce"),
    PO1G("Gniezno"),
    SZ1O("Goleniów"),
    TO1G("Golub-Dobrzyń"),
    NS1G("Gorlice"),
    GW1G("Gorzów Wielkopolski"),
    PL1G("Gostynin"),
    PO1Y("Gostyń"),
    LM1G("Grajewo"),
    WA1G("Grodzisk Mazowiecki"),
    PO1S("Grodzisk Wlkp. "),
    RA1G("Grójec"),
    TO1U("Grudziądz"),
    SZ1G("Gryfice"),
    SZ1Y("Gryfino"),
    ZG2K("Gubin"),
    BI2P("Hajnówka"),
    ZA1H("Hrubieszów"),
    EL1I("Iława"),
    BY1I("Inowrocław"),
    ZA1J("Janów Lubelski"),
    KZ1J("Jarocin"),
    PR1J("Jarosław"),
    KS1J("Jasło"),
    GL1J("Jastrzębie-Zdrój"),
    LE1J("Jawor"),
    KA1J("Jaworzno"),
    JG1J("Jelenia Góra"),
    KI1J("Jędrzejów"),
    KZ1A("Kalisz"),
    JG1K("Kamienna Góra"),
    SZ1K("Kamień Pomorski"),
    GD1R("Kartuzy"),
    KA1K("Katowice"),
    KI1I("Kazimierza wielka"),
    OP1K("Kędzierzyn-koźle"),
    KZ1E("Kępno"),
    OL1K("Kętrzyn"),
    KR2E("Kęty"),
    KI1L("Kielce"),
    OP1U("Kluczbork"),
    CZ2C("Kłobuck"),
    SW1K("Kłodzko"),
    TB1K("Kolbuszowa"),
    KO1L("Kołobrzeg"),
    KN1K("Koło"),
    KN1N("Konin"),
    KI1K("Końskie"),
    KO1K("Koszalin"),
    PO1K("Kościan"),
    GD1E("Kościerzyna"),
    RA1K("Kozienice"),
    KR1P("Kraków"),
    ZA1K("Krasnystaw"),
    LU1K("Kraśnik"),
    KS1K("Krosno"),
    ZG1K("Krosno Odrzańskie"),
    KZ1R("Krotoszyn"),
    KR2K("Krzeszowice"),
    LD1K("Kutno"),
    GD1I("Kwidzyn"),
    WA1L("Legionowo"),
    LE1L("Legnica"),
    KS1E("Lesko"),
    PO1L("Leszno"),
    RZ1E("Leżajsk"),
    SL1L("Lębork"),
    OL1L("Lidzbark Warmiński"),
    NS1L("Limanowa"),
    WL1L("Lipno"),
    RA1L("Lipsko"),
    PR1L("Lubaczów"),
    JG1L("Lubań"),
    LU1A("Lubartów"),
    LE1U("Lubin"),
    CZ1L("Lubliniec"),
    LU1I("Lublin"),
    JG1S("Lwówek Śląski"),
    RZ1A("Łańcut"),
    SR1L("Łask"),
    LD1Y("Łęczyca"),
    SZ1L("Łobez"),
    LM1L("Łomża"),
    SI2S("Łosice"),
    LD1O("Łowicz"),
    LD1M("Łódź"),
    LU1U("Łuków"),
    GD1M("Malbork"),
    SL1M("Miastko"),
    KR1M("Miechów"),
    TB1M("Mielec"),
    PO2A("Międzychód"),
    GW1M("Międzyrzecz"),
    KA1M("Mikołów"),
    WR1M("Milicz"),
    SI1M("Mińsk Mazowiecki"),
    PL1M("Mława"),
    BY1M("Mogilno"),
    EL2O("Morąg"),
    OL1M("Mrągowo"),
    NS2L("Mszana Dolna"),
    NS1M("Muszyna"),
    KA1L("Mysłowice"),
    CZ1M("Myszków"),
    KR1Y("Myślenice"),
    SZ1M("Myślibórz"),
    BY1N("Nakło nad Notecią"),
    OL1N("Nidzica"),
    KR2I("Niepołomice"),
    TB1N("Nisko"),
    SW2K("Nowa Ruda"),
    ZG1N("Nowa Sól"),
    EL1N("Nowe Miasto Lubawskie"),
    GD2M("Nowy Dwór Gdański"),
    WA1N("Nowy Dwór Mazowiecki"),
    NS1S("Nowy Sącz"),
    NS1T("Nowy Targ"),
    PO1N("Nowy Tomyśl"),
    OP1N("Nysa"),
    PO1O("Oborniki"),
    OL1C("Olecko"),
    OP1L("Olesno"),
    WR1E("Oleśnica"),
    KR1O("Olkusz"),
    OL1O("Olsztyn"),
    WR1O("Oława"),
    KI1T("Opatów"),
    PT1O("Opoczno"),
    LU1O("Opole Lubelskie"),
    OP1O("Opole"),
    OS1O("Ostrołęka"),
    KI1O("Ostrowiec Świętokrzyski"),
    EL1O("Ostróda"),
    OS1M("Ostrów Mazowiecka"),
    KZ1W("Ostrów Wielkopolski"),
    KZ1O("Ostrzeszów"),
    KR1E("Oświęcim"),
    WA1O("Otwock"),
    LD1P("Pabianice"),
    SR2W("Pajęczno"),
    WA1I("Piaseczno"),
    PO1I("Piła"),
    KI1P("Pińczów"),
    RA2Z("Pionki"),
    PT1P("Piotrków Trybunalski"),
    OL1P("Pisz"),
    KZ1P("Pleszew"),
    PL1P("Płock"),
    PL1L("Płońsk"),
    SR2L("Poddębice"),
    SZ2S("Police"),
    PO1P("Poznań (V)"),
    PO2P("Poznań (VI)"),
    KR1H("Proszowice"),
    OP1P("Prudnik"),
    WA1P("Pruszków"),
    OS1P("Przasnysz"),
    PR1P("Przemyśl"),
    PR1R("Przeworsk"),
    RA1P("Przysucha"),
    KA1P("Pszczyna"),
    GD2W("Puck"),
    LU1P("Puławy"),
    OS1U("Pułtusk"),
    SZ2T("Pyrzyce"),
    GL1R("Racibórz"),
    RA1R("Radom"),
    PT1R("Radomsko"),
    WL1R("Radziejów"),
    LU1R("Radzyń Podlaski"),
    LD1R("Rawa Mazowiecka"),
    PO1R("Rawicz"),
    RZ1R("Ropczyce"),
    GL1S("Ruda Śląska"),
    GL1Y("Rybnik"),
    LU1Y("Ryki"),
    WL1Y("Rypin"),
    RZ1Z("Rzeszów"),
    KI1S("Sandomierz"),
    KS1S("Sanok"),
    SU1N("Sejny"),
    BY2T("Sępólno Krajeńskie"),
    SI1S("Siedlce"),
    KA1I("Siemianowice Śląskie"),
    BI3P("Siemiatycze"),
    PR2R("Sieniawa"),
    SR1S("Sieradz"),
    PL1E("Sierpc"),
    KR2P("Skała"),
    KI1R("Skarżysko-Kamienna"),
    KR3I("Skawina"),
    LD1H("Skierniewice"),
    KO1E("Sławno"),
    KR1S("Słomniki"),
    GW1S("Słubice"),
    KN1S("Słupca"),
    SL1S("Słupsk"),
    PL1O("Sochaczew"),
    SI1P("Sokołów Podlaski"),
    BI1S("Sokółka"),
    GD1S("Sopot"),
    KA1S("Sosnowiec"),
    TB1S("Stalowa Wola"),
    KI1H("Starachowice"),
    SZ1T("Stargard Szczeciński"),
    GD1A("Starogard Gdański"),
    KI1A("Staszów"),
    GW1K("Strzelce Krajeńskie"),
    OP1S("Strzelce Opolskie"),
    WR1T("Strzelin"),
    RZ1S("Strzyżów"),
    KR1B("Sucha Beskidzka"),
    ZG2S("Sulechów"),
    GW1U("Sulęcin"),
    SU1S("Suwałki"),
    PO1A("Szamotuły"),
    KO1I("Szczecinek"),
    SZ1S("Szczecin"),
    OL1S("Szczytno"),
    GD2I("Sztum"),
    BY1U("Szubin"),
    RA1S("Szydłowiec"),
    PO1M("Śrem"),
    WR1S("Środa Śląska"),
    PO1D("Środa Wlkp."),
    SW1S("Świdnica"),
    KO2B("Świdwin"),
    ZG1S("Świebodzin"),
    BY1S("Świecie"),
    SZ1W("Świnoujście"),
    TB1T("Tarnobrzeg"),
    GL1T("Tarnowskie Góry"),
    TR1T("Tarnów"),
    GD1T("Tczew"),
    ZA1T("Tomaszów Lubelski"),
    PT1T("Tomaszów Mazowiecki"),
    TO1T("Toruń"),
    PO1T("Trzcianka"),
    WR1W("Trzebnica"),
    BY1T("Tuchola"),
    TR2T("Tuchów"),
    KN1T("Turek"),
    KA1T("Tychy"),
    RZ2Z("Tyczyn"),
    KS2E("Ustrzyki Dolne"),
    KR1W("Wadowice"),
    SW1W("Wałbrzych"),
    KO1W("Wałcz"),
    WA3M("Warszawa (IX)"),
    WA1M("Warszawa (VI)"),
    WA2M("Warszawa (VII)"),
    WA4M("Warszawa (X)"),
    WA5M("Warszawa (XIII)"),
    WA6M("Warszawa (XV)"),
    TO1W("Wąbrzeźno"),
    PO1B("Wągrowiec"),
    GD1W("Wejherowo"),
    OL2G("Węgorzewo"),
    SI1W("Węgrów"),
    KR1I("Wieliczka"),
    SR1W("Wieluń"),
    WL1W("Włocławek"),
    LU1W("Włodawa"),
    KI1W("Włoszczowa"),
    GL1W("Wodzisław Śląski"),
    PO1E("Wolsztyn"),
    WA1W("Wołomin"),
    WR1L("Wołów"),
    WR1K("Wrocław"),
    PO1F("Września"),
    ZG1W("Wschowa"),
    PO2H("Wyrzysk"),
    LM1W("Wysokie Mazowieckie"),
    OS1W("Wyszków"),
    GL1Z("Zabrze"),
    NS1Z("Zakopane"),
    LM1Z("Zambrów"),
    ZA1Z("Zamość"),
    CZ1Z("Zawiercie"),
    SW1Z("Ząbkowice Śląskie"),
    SR1Z("Zduńska Wola"),
    LD1G("Zgierz"),
    JG1Z("Zgorzelec"),
    ZG1E("Zielona Góra"),
    LE1Z("Złotoryja"),
    PO1Z("Złotów"),
    RA1Z("Zwoleń"),
    ZG1G("Żagań"),
    ZG1R("Żary"),
    BY1Z("Żnin"),
    GL1X("Żory"),
    PL2M("Żuromin"),
    PL1Z("Żyrardów"),
    BB1Z("Żywiec");

    private final String name;

    Court(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
